# This test workflow is supposed to run a simple r script that writes a file (deletethis.txt) that contains the current day/time
# It is based upon the following example: https://ropenscilabs.github.io/actions_sandbox/understanding-yaml.html#r-syntax-options
name: test workflow
on:
  schedule:
    # * is a special character in YAML so you have to quote this string - change cron string to '0 * 7 * *' to run once on the 7th day of the month
    - cron:  '0 * 7 * *'
      
jobs:
  render:
    name: Run r script
    runs-on: ubuntu-latest
    steps:
     - uses: actions/checkout@v1
     - uses: r-lib/actions/setup-r@v1
     - name: install R packages
       # Add packages needed by R functions for calculating average SST 
       # run: Rscript -e 'install.packages(c("here", "rgdal", "raster", "rerddap", "glue", "sf", "fs", "tidyverse", "lubridate"))'
       run: Rscript -e 'install.packages("devtools")'

       # run the r script which generates the file with the current day/time
     - name: Run test R script
       run: Rscript -e 'source("scripts/test_script2.r")'
     - name: Commit file      
       run: | 
        git config --global user.email "${{secrets.GH_EMAIL}}"; git config --global user.name "${{github.actor}}"
        git add -A; git commit -a -m 'Create deletethis.txt' || echo "No changes to commit"
        git push https://${{github.actor}}:${{secrets.GH_PAT}}@github.com/${{github.repository}}.git HEAD:${{ github.ref }} || echo "No changes to commit"
